/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Day la vi du ve default value cua mot so loai du lieu */
@org.apache.avro.specific.AvroGenerated
public class DefaultValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6801809156405328912L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DefaultValue\",\"namespace\":\"congnghetuts.com.avro\",\"doc\":\"Day la vi du ve default value cua mot so loai du lieu\",\"fields\":[{\"name\":\"status\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"length\",\"type\":[\"null\",\"double\"]},{\"name\":\"size\",\"type\":[\"null\",\"float\"]},{\"name\":\"objectType\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ObjectType\",\"doc\":\"Day la vi du ve ObjectType\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"int\"]},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}]},{\"name\":\"arraylists\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}]},{\"name\":\"arrayStringLists\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"name\":\"recordN\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Record\",\"fields\":[{\"name\":\"enable\",\"type\":[\"null\",\"boolean\"]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DefaultValue> ENCODER =
      new BinaryMessageEncoder<DefaultValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DefaultValue> DECODER =
      new BinaryMessageDecoder<DefaultValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DefaultValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DefaultValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DefaultValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DefaultValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DefaultValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DefaultValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DefaultValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DefaultValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Boolean status;
   private java.lang.Double length;
   private java.lang.Float size;
   private congnghetuts.com.avro.ObjectType objectType;
   private java.util.List<java.lang.Integer> arraylists;
   private java.util.List<java.lang.String> arrayStringLists;
   private congnghetuts.com.avro.Record recordN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DefaultValue() {}

  /**
   * All-args constructor.
   * @param status The new value for status
   * @param length The new value for length
   * @param size The new value for size
   * @param objectType The new value for objectType
   * @param arraylists The new value for arraylists
   * @param arrayStringLists The new value for arrayStringLists
   * @param recordN The new value for recordN
   */
  public DefaultValue(java.lang.Boolean status, java.lang.Double length, java.lang.Float size, congnghetuts.com.avro.ObjectType objectType, java.util.List<java.lang.Integer> arraylists, java.util.List<java.lang.String> arrayStringLists, congnghetuts.com.avro.Record recordN) {
    this.status = status;
    this.length = length;
    this.size = size;
    this.objectType = objectType;
    this.arraylists = arraylists;
    this.arrayStringLists = arrayStringLists;
    this.recordN = recordN;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return length;
    case 2: return size;
    case 3: return objectType;
    case 4: return arraylists;
    case 5: return arrayStringLists;
    case 6: return recordN;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (java.lang.Boolean)value$; break;
    case 1: length = (java.lang.Double)value$; break;
    case 2: size = (java.lang.Float)value$; break;
    case 3: objectType = (congnghetuts.com.avro.ObjectType)value$; break;
    case 4: arraylists = (java.util.List<java.lang.Integer>)value$; break;
    case 5: arrayStringLists = (java.util.List<java.lang.String>)value$; break;
    case 6: recordN = (congnghetuts.com.avro.Record)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.Boolean getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Boolean value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'length' field.
   * @return The value of the 'length' field.
   */
  public java.lang.Double getLength() {
    return length;
  }


  /**
   * Sets the value of the 'length' field.
   * @param value the value to set.
   */
  public void setLength(java.lang.Double value) {
    this.length = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public java.lang.Float getSize() {
    return size;
  }


  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Float value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'objectType' field.
   * @return The value of the 'objectType' field.
   */
  public congnghetuts.com.avro.ObjectType getObjectType() {
    return objectType;
  }


  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(congnghetuts.com.avro.ObjectType value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'arraylists' field.
   * @return The value of the 'arraylists' field.
   */
  public java.util.List<java.lang.Integer> getArraylists() {
    return arraylists;
  }


  /**
   * Sets the value of the 'arraylists' field.
   * @param value the value to set.
   */
  public void setArraylists(java.util.List<java.lang.Integer> value) {
    this.arraylists = value;
  }

  /**
   * Gets the value of the 'arrayStringLists' field.
   * @return The value of the 'arrayStringLists' field.
   */
  public java.util.List<java.lang.String> getArrayStringLists() {
    return arrayStringLists;
  }


  /**
   * Sets the value of the 'arrayStringLists' field.
   * @param value the value to set.
   */
  public void setArrayStringLists(java.util.List<java.lang.String> value) {
    this.arrayStringLists = value;
  }

  /**
   * Gets the value of the 'recordN' field.
   * @return The value of the 'recordN' field.
   */
  public congnghetuts.com.avro.Record getRecordN() {
    return recordN;
  }


  /**
   * Sets the value of the 'recordN' field.
   * @param value the value to set.
   */
  public void setRecordN(congnghetuts.com.avro.Record value) {
    this.recordN = value;
  }

  /**
   * Creates a new DefaultValue RecordBuilder.
   * @return A new DefaultValue RecordBuilder
   */
  public static congnghetuts.com.avro.DefaultValue.Builder newBuilder() {
    return new congnghetuts.com.avro.DefaultValue.Builder();
  }

  /**
   * Creates a new DefaultValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DefaultValue RecordBuilder
   */
  public static congnghetuts.com.avro.DefaultValue.Builder newBuilder(congnghetuts.com.avro.DefaultValue.Builder other) {
    if (other == null) {
      return new congnghetuts.com.avro.DefaultValue.Builder();
    } else {
      return new congnghetuts.com.avro.DefaultValue.Builder(other);
    }
  }

  /**
   * Creates a new DefaultValue RecordBuilder by copying an existing DefaultValue instance.
   * @param other The existing instance to copy.
   * @return A new DefaultValue RecordBuilder
   */
  public static congnghetuts.com.avro.DefaultValue.Builder newBuilder(congnghetuts.com.avro.DefaultValue other) {
    if (other == null) {
      return new congnghetuts.com.avro.DefaultValue.Builder();
    } else {
      return new congnghetuts.com.avro.DefaultValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for DefaultValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DefaultValue>
    implements org.apache.avro.data.RecordBuilder<DefaultValue> {

    private java.lang.Boolean status;
    private java.lang.Double length;
    private java.lang.Float size;
    private congnghetuts.com.avro.ObjectType objectType;
    private congnghetuts.com.avro.ObjectType.Builder objectTypeBuilder;
    private java.util.List<java.lang.Integer> arraylists;
    private java.util.List<java.lang.String> arrayStringLists;
    private congnghetuts.com.avro.Record recordN;
    private congnghetuts.com.avro.Record.Builder recordNBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(congnghetuts.com.avro.DefaultValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.length)) {
        this.length = data().deepCopy(fields()[1].schema(), other.length);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.size)) {
        this.size = data().deepCopy(fields()[2].schema(), other.size);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.objectType)) {
        this.objectType = data().deepCopy(fields()[3].schema(), other.objectType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasObjectTypeBuilder()) {
        this.objectTypeBuilder = congnghetuts.com.avro.ObjectType.newBuilder(other.getObjectTypeBuilder());
      }
      if (isValidValue(fields()[4], other.arraylists)) {
        this.arraylists = data().deepCopy(fields()[4].schema(), other.arraylists);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.arrayStringLists)) {
        this.arrayStringLists = data().deepCopy(fields()[5].schema(), other.arrayStringLists);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.recordN)) {
        this.recordN = data().deepCopy(fields()[6].schema(), other.recordN);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (other.hasRecordNBuilder()) {
        this.recordNBuilder = congnghetuts.com.avro.Record.newBuilder(other.getRecordNBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DefaultValue instance
     * @param other The existing instance to copy.
     */
    private Builder(congnghetuts.com.avro.DefaultValue other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.length)) {
        this.length = data().deepCopy(fields()[1].schema(), other.length);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.size)) {
        this.size = data().deepCopy(fields()[2].schema(), other.size);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.objectType)) {
        this.objectType = data().deepCopy(fields()[3].schema(), other.objectType);
        fieldSetFlags()[3] = true;
      }
      this.objectTypeBuilder = null;
      if (isValidValue(fields()[4], other.arraylists)) {
        this.arraylists = data().deepCopy(fields()[4].schema(), other.arraylists);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.arrayStringLists)) {
        this.arrayStringLists = data().deepCopy(fields()[5].schema(), other.arrayStringLists);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.recordN)) {
        this.recordN = data().deepCopy(fields()[6].schema(), other.recordN);
        fieldSetFlags()[6] = true;
      }
      this.recordNBuilder = null;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.Boolean getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setStatus(java.lang.Boolean value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearStatus() {
      status = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'length' field.
      * @return The value.
      */
    public java.lang.Double getLength() {
      return length;
    }


    /**
      * Sets the value of the 'length' field.
      * @param value The value of 'length'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setLength(java.lang.Double value) {
      validate(fields()[1], value);
      this.length = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'length' field has been set.
      * @return True if the 'length' field has been set, false otherwise.
      */
    public boolean hasLength() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'length' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearLength() {
      length = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public java.lang.Float getSize() {
      return size;
    }


    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setSize(java.lang.Float value) {
      validate(fields()[2], value);
      this.size = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearSize() {
      size = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'objectType' field.
      * @return The value.
      */
    public congnghetuts.com.avro.ObjectType getObjectType() {
      return objectType;
    }


    /**
      * Sets the value of the 'objectType' field.
      * @param value The value of 'objectType'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setObjectType(congnghetuts.com.avro.ObjectType value) {
      validate(fields()[3], value);
      this.objectTypeBuilder = null;
      this.objectType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'objectType' field has been set.
      * @return True if the 'objectType' field has been set, false otherwise.
      */
    public boolean hasObjectType() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'objectType' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public congnghetuts.com.avro.ObjectType.Builder getObjectTypeBuilder() {
      if (objectTypeBuilder == null) {
        if (hasObjectType()) {
          setObjectTypeBuilder(congnghetuts.com.avro.ObjectType.newBuilder(objectType));
        } else {
          setObjectTypeBuilder(congnghetuts.com.avro.ObjectType.newBuilder());
        }
      }
      return objectTypeBuilder;
    }

    /**
     * Sets the Builder instance for the 'objectType' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public congnghetuts.com.avro.DefaultValue.Builder setObjectTypeBuilder(congnghetuts.com.avro.ObjectType.Builder value) {
      clearObjectType();
      objectTypeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'objectType' field has an active Builder instance
     * @return True if the 'objectType' field has an active Builder instance
     */
    public boolean hasObjectTypeBuilder() {
      return objectTypeBuilder != null;
    }

    /**
      * Clears the value of the 'objectType' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearObjectType() {
      objectType = null;
      objectTypeBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'arraylists' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getArraylists() {
      return arraylists;
    }


    /**
      * Sets the value of the 'arraylists' field.
      * @param value The value of 'arraylists'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setArraylists(java.util.List<java.lang.Integer> value) {
      validate(fields()[4], value);
      this.arraylists = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'arraylists' field has been set.
      * @return True if the 'arraylists' field has been set, false otherwise.
      */
    public boolean hasArraylists() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'arraylists' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearArraylists() {
      arraylists = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrayStringLists' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getArrayStringLists() {
      return arrayStringLists;
    }


    /**
      * Sets the value of the 'arrayStringLists' field.
      * @param value The value of 'arrayStringLists'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setArrayStringLists(java.util.List<java.lang.String> value) {
      validate(fields()[5], value);
      this.arrayStringLists = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'arrayStringLists' field has been set.
      * @return True if the 'arrayStringLists' field has been set, false otherwise.
      */
    public boolean hasArrayStringLists() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'arrayStringLists' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearArrayStringLists() {
      arrayStringLists = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordN' field.
      * @return The value.
      */
    public congnghetuts.com.avro.Record getRecordN() {
      return recordN;
    }


    /**
      * Sets the value of the 'recordN' field.
      * @param value The value of 'recordN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder setRecordN(congnghetuts.com.avro.Record value) {
      validate(fields()[6], value);
      this.recordNBuilder = null;
      this.recordN = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'recordN' field has been set.
      * @return True if the 'recordN' field has been set, false otherwise.
      */
    public boolean hasRecordN() {
      return fieldSetFlags()[6];
    }

    /**
     * Gets the Builder instance for the 'recordN' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public congnghetuts.com.avro.Record.Builder getRecordNBuilder() {
      if (recordNBuilder == null) {
        if (hasRecordN()) {
          setRecordNBuilder(congnghetuts.com.avro.Record.newBuilder(recordN));
        } else {
          setRecordNBuilder(congnghetuts.com.avro.Record.newBuilder());
        }
      }
      return recordNBuilder;
    }

    /**
     * Sets the Builder instance for the 'recordN' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public congnghetuts.com.avro.DefaultValue.Builder setRecordNBuilder(congnghetuts.com.avro.Record.Builder value) {
      clearRecordN();
      recordNBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'recordN' field has an active Builder instance
     * @return True if the 'recordN' field has an active Builder instance
     */
    public boolean hasRecordNBuilder() {
      return recordNBuilder != null;
    }

    /**
      * Clears the value of the 'recordN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.DefaultValue.Builder clearRecordN() {
      recordN = null;
      recordNBuilder = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DefaultValue build() {
      try {
        DefaultValue record = new DefaultValue();
        record.status = fieldSetFlags()[0] ? this.status : (java.lang.Boolean) defaultValue(fields()[0]);
        record.length = fieldSetFlags()[1] ? this.length : (java.lang.Double) defaultValue(fields()[1]);
        record.size = fieldSetFlags()[2] ? this.size : (java.lang.Float) defaultValue(fields()[2]);
        if (objectTypeBuilder != null) {
          try {
            record.objectType = this.objectTypeBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("objectType"));
            throw e;
          }
        } else {
          record.objectType = fieldSetFlags()[3] ? this.objectType : (congnghetuts.com.avro.ObjectType) defaultValue(fields()[3]);
        }
        record.arraylists = fieldSetFlags()[4] ? this.arraylists : (java.util.List<java.lang.Integer>) defaultValue(fields()[4]);
        record.arrayStringLists = fieldSetFlags()[5] ? this.arrayStringLists : (java.util.List<java.lang.String>) defaultValue(fields()[5]);
        if (recordNBuilder != null) {
          try {
            record.recordN = this.recordNBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("recordN"));
            throw e;
          }
        } else {
          record.recordN = fieldSetFlags()[6] ? this.recordN : (congnghetuts.com.avro.Record) defaultValue(fields()[6]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DefaultValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<DefaultValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DefaultValue>
    READER$ = (org.apache.avro.io.DatumReader<DefaultValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.status);
    }

    if (this.length == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.length);
    }

    if (this.size == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeFloat(this.size);
    }

    if (this.objectType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.objectType.customEncode(out);
    }

    if (this.arraylists == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.arraylists.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.Integer e0: this.arraylists) {
        actualSize0++;
        out.startItem();
        out.writeInt(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.arrayStringLists == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size1 = this.arrayStringLists.size();
      out.writeArrayStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.lang.String e1: this.arrayStringLists) {
        actualSize1++;
        out.startItem();
        out.writeString(e1);
      }
      out.writeArrayEnd();
      if (actualSize1 != size1)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }

    if (this.recordN == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.recordN.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.length = null;
      } else {
        this.length = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.size = null;
      } else {
        this.size = in.readFloat();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.objectType = null;
      } else {
        if (this.objectType == null) {
          this.objectType = new congnghetuts.com.avro.ObjectType();
        }
        this.objectType.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.arraylists = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.Integer> a0 = this.arraylists;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("arraylists").schema().getTypes().get(1));
          this.arraylists = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readInt();
            a0.add(e0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.arrayStringLists = null;
      } else {
        long size1 = in.readArrayStart();
        java.util.List<java.lang.String> a1 = this.arrayStringLists;
        if (a1 == null) {
          a1 = new SpecificData.Array<java.lang.String>((int)size1, SCHEMA$.getField("arrayStringLists").schema().getTypes().get(1));
          this.arrayStringLists = a1;
        } else a1.clear();
        SpecificData.Array<java.lang.String> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a1 : null);
        for ( ; 0 < size1; size1 = in.arrayNext()) {
          for ( ; size1 != 0; size1--) {
            java.lang.String e1 = (ga1 != null ? ga1.peek() : null);
            e1 = in.readString();
            a1.add(e1);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.recordN = null;
      } else {
        if (this.recordN == null) {
          this.recordN = new congnghetuts.com.avro.Record();
        }
        this.recordN.customDecode(in);
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readBoolean();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.length = null;
          } else {
            this.length = in.readDouble();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.size = null;
          } else {
            this.size = in.readFloat();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.objectType = null;
          } else {
            if (this.objectType == null) {
              this.objectType = new congnghetuts.com.avro.ObjectType();
            }
            this.objectType.customDecode(in);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.arraylists = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.Integer> a0 = this.arraylists;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("arraylists").schema().getTypes().get(1));
              this.arraylists = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readInt();
                a0.add(e0);
              }
            }
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.arrayStringLists = null;
          } else {
            long size1 = in.readArrayStart();
            java.util.List<java.lang.String> a1 = this.arrayStringLists;
            if (a1 == null) {
              a1 = new SpecificData.Array<java.lang.String>((int)size1, SCHEMA$.getField("arrayStringLists").schema().getTypes().get(1));
              this.arrayStringLists = a1;
            } else a1.clear();
            SpecificData.Array<java.lang.String> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a1 : null);
            for ( ; 0 < size1; size1 = in.arrayNext()) {
              for ( ; size1 != 0; size1--) {
                java.lang.String e1 = (ga1 != null ? ga1.peek() : null);
                e1 = in.readString();
                a1.add(e1);
              }
            }
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.recordN = null;
          } else {
            if (this.recordN == null) {
              this.recordN = new congnghetuts.com.avro.Record();
            }
            this.recordN.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










