/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;
/** Day la enum */
@org.apache.avro.specific.AvroGenerated
public enum enumTest implements org.apache.avro.generic.GenericEnumSymbol<enumTest> {
  value1, value2, all  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\"," +
          "\"name\":\"enumTest\",\"namespace\":\"congnghetuts.com.avro\",\"doc\":\"Day la enum\",\"symbols\":[\"value1\",\"value2\",\"all\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
