/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Vi du ve fixed type */
@org.apache.avro.specific.AvroGenerated
public class fixedTest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7064190130141233657L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"fixedTest\",\"namespace\":\"congnghetuts.com.avro\",\"doc\":\"Vi du ve fixed type\",\"fields\":[{\"name\":\"fixedN\",\"type\":{\"type\":\"fixed\",\"name\":\"FixedN\",\"size\":10}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<fixedTest> ENCODER =
      new BinaryMessageEncoder<fixedTest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<fixedTest> DECODER =
      new BinaryMessageDecoder<fixedTest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<fixedTest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<fixedTest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<fixedTest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<fixedTest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this fixedTest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a fixedTest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a fixedTest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static fixedTest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private congnghetuts.com.avro.FixedN fixedN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public fixedTest() {}

  /**
   * All-args constructor.
   * @param fixedN The new value for fixedN
   */
  public fixedTest(congnghetuts.com.avro.FixedN fixedN) {
    this.fixedN = fixedN;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fixedN;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fixedN = (congnghetuts.com.avro.FixedN)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fixedN' field.
   * @return The value of the 'fixedN' field.
   */
  public congnghetuts.com.avro.FixedN getFixedN() {
    return fixedN;
  }


  /**
   * Sets the value of the 'fixedN' field.
   * @param value the value to set.
   */
  public void setFixedN(congnghetuts.com.avro.FixedN value) {
    this.fixedN = value;
  }

  /**
   * Creates a new fixedTest RecordBuilder.
   * @return A new fixedTest RecordBuilder
   */
  public static congnghetuts.com.avro.fixedTest.Builder newBuilder() {
    return new congnghetuts.com.avro.fixedTest.Builder();
  }

  /**
   * Creates a new fixedTest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new fixedTest RecordBuilder
   */
  public static congnghetuts.com.avro.fixedTest.Builder newBuilder(congnghetuts.com.avro.fixedTest.Builder other) {
    if (other == null) {
      return new congnghetuts.com.avro.fixedTest.Builder();
    } else {
      return new congnghetuts.com.avro.fixedTest.Builder(other);
    }
  }

  /**
   * Creates a new fixedTest RecordBuilder by copying an existing fixedTest instance.
   * @param other The existing instance to copy.
   * @return A new fixedTest RecordBuilder
   */
  public static congnghetuts.com.avro.fixedTest.Builder newBuilder(congnghetuts.com.avro.fixedTest other) {
    if (other == null) {
      return new congnghetuts.com.avro.fixedTest.Builder();
    } else {
      return new congnghetuts.com.avro.fixedTest.Builder(other);
    }
  }

  /**
   * RecordBuilder for fixedTest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<fixedTest>
    implements org.apache.avro.data.RecordBuilder<fixedTest> {

    private congnghetuts.com.avro.FixedN fixedN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(congnghetuts.com.avro.fixedTest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fixedN)) {
        this.fixedN = data().deepCopy(fields()[0].schema(), other.fixedN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing fixedTest instance
     * @param other The existing instance to copy.
     */
    private Builder(congnghetuts.com.avro.fixedTest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.fixedN)) {
        this.fixedN = data().deepCopy(fields()[0].schema(), other.fixedN);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'fixedN' field.
      * @return The value.
      */
    public congnghetuts.com.avro.FixedN getFixedN() {
      return fixedN;
    }


    /**
      * Sets the value of the 'fixedN' field.
      * @param value The value of 'fixedN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.fixedTest.Builder setFixedN(congnghetuts.com.avro.FixedN value) {
      validate(fields()[0], value);
      this.fixedN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fixedN' field has been set.
      * @return True if the 'fixedN' field has been set, false otherwise.
      */
    public boolean hasFixedN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fixedN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.fixedTest.Builder clearFixedN() {
      fixedN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public fixedTest build() {
      try {
        fixedTest record = new fixedTest();
        record.fixedN = fieldSetFlags()[0] ? this.fixedN : (congnghetuts.com.avro.FixedN) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<fixedTest>
    WRITER$ = (org.apache.avro.io.DatumWriter<fixedTest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<fixedTest>
    READER$ = (org.apache.avro.io.DatumReader<fixedTest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeFixed(this.fixedN.bytes(), 0, 10);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.fixedN == null) {
        this.fixedN = new congnghetuts.com.avro.FixedN();
      }
      in.readFixed(this.fixedN.bytes(), 0, 10);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.fixedN == null) {
            this.fixedN = new congnghetuts.com.avro.FixedN();
          }
          in.readFixed(this.fixedN.bytes(), 0, 10);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










