/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;
@org.apache.avro.specific.FixedSize(10)
@org.apache.avro.specific.AvroGenerated
public class FixedN extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = -3723329931042216013L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"FixedN\",\"namespace\":\"congnghetuts.com.avro\",\"size\":10}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new FixedN */
  public FixedN() {
    super();
  }

  /**
   * Creates a new FixedN with the given bytes.
   * @param bytes The bytes to create the new FixedN.
   */
  public FixedN(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter<FixedN>
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<FixedN>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader<FixedN>
    READER$ = new org.apache.avro.specific.SpecificDatumReader<FixedN>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
