/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Vi du map type */
@org.apache.avro.specific.AvroGenerated
public class mapTest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1875272051707343716L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"mapTest\",\"namespace\":\"congnghetuts.com.avro\",\"doc\":\"Vi du map type\",\"fields\":[{\"name\":\"mapN\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<mapTest> ENCODER =
      new BinaryMessageEncoder<mapTest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<mapTest> DECODER =
      new BinaryMessageDecoder<mapTest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<mapTest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<mapTest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<mapTest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<mapTest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this mapTest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a mapTest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a mapTest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static mapTest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.Map<java.lang.String,java.lang.String> mapN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public mapTest() {}

  /**
   * All-args constructor.
   * @param mapN The new value for mapN
   */
  public mapTest(java.util.Map<java.lang.String,java.lang.String> mapN) {
    this.mapN = mapN;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mapN;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mapN = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mapN' field.
   * @return The value of the 'mapN' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getMapN() {
    return mapN;
  }


  /**
   * Sets the value of the 'mapN' field.
   * @param value the value to set.
   */
  public void setMapN(java.util.Map<java.lang.String,java.lang.String> value) {
    this.mapN = value;
  }

  /**
   * Creates a new mapTest RecordBuilder.
   * @return A new mapTest RecordBuilder
   */
  public static congnghetuts.com.avro.mapTest.Builder newBuilder() {
    return new congnghetuts.com.avro.mapTest.Builder();
  }

  /**
   * Creates a new mapTest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new mapTest RecordBuilder
   */
  public static congnghetuts.com.avro.mapTest.Builder newBuilder(congnghetuts.com.avro.mapTest.Builder other) {
    if (other == null) {
      return new congnghetuts.com.avro.mapTest.Builder();
    } else {
      return new congnghetuts.com.avro.mapTest.Builder(other);
    }
  }

  /**
   * Creates a new mapTest RecordBuilder by copying an existing mapTest instance.
   * @param other The existing instance to copy.
   * @return A new mapTest RecordBuilder
   */
  public static congnghetuts.com.avro.mapTest.Builder newBuilder(congnghetuts.com.avro.mapTest other) {
    if (other == null) {
      return new congnghetuts.com.avro.mapTest.Builder();
    } else {
      return new congnghetuts.com.avro.mapTest.Builder(other);
    }
  }

  /**
   * RecordBuilder for mapTest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<mapTest>
    implements org.apache.avro.data.RecordBuilder<mapTest> {

    private java.util.Map<java.lang.String,java.lang.String> mapN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(congnghetuts.com.avro.mapTest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mapN)) {
        this.mapN = data().deepCopy(fields()[0].schema(), other.mapN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing mapTest instance
     * @param other The existing instance to copy.
     */
    private Builder(congnghetuts.com.avro.mapTest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.mapN)) {
        this.mapN = data().deepCopy(fields()[0].schema(), other.mapN);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'mapN' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getMapN() {
      return mapN;
    }


    /**
      * Sets the value of the 'mapN' field.
      * @param value The value of 'mapN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.mapTest.Builder setMapN(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[0], value);
      this.mapN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mapN' field has been set.
      * @return True if the 'mapN' field has been set, false otherwise.
      */
    public boolean hasMapN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mapN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.mapTest.Builder clearMapN() {
      mapN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public mapTest build() {
      try {
        mapTest record = new mapTest();
        record.mapN = fieldSetFlags()[0] ? this.mapN : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<mapTest>
    WRITER$ = (org.apache.avro.io.DatumWriter<mapTest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<mapTest>
    READER$ = (org.apache.avro.io.DatumReader<mapTest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.mapN.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> e0: this.mapN.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.String v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.String,java.lang.String> m0 = this.mapN; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)size0);
        this.mapN = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String k0 = null;
          k0 = in.readString();
          java.lang.String v0 = null;
          v0 = in.readString();
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.String,java.lang.String> m0 = this.mapN; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)size0);
            this.mapN = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String k0 = null;
              k0 = in.readString();
              java.lang.String v0 = null;
              v0 = in.readString();
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










