/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package congnghetuts.com.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Day la model su dung primary type */
@org.apache.avro.specific.AvroGenerated
public class PrimaryType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3814413931846111589L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PrimaryType\",\"namespace\":\"congnghetuts.com.avro\",\"doc\":\"Day la model su dung primary type\",\"fields\":[{\"name\":\"intN\",\"type\":\"int\"},{\"name\":\"stringN\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"nullN\",\"type\":\"null\"},{\"name\":\"floatN\",\"type\":\"float\"},{\"name\":\"longN\",\"type\":\"long\"},{\"name\":\"booleanN\",\"type\":\"boolean\"},{\"name\":\"bytesN\",\"type\":\"bytes\"},{\"name\":\"doubleN\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PrimaryType> ENCODER =
      new BinaryMessageEncoder<PrimaryType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PrimaryType> DECODER =
      new BinaryMessageDecoder<PrimaryType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PrimaryType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PrimaryType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PrimaryType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PrimaryType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PrimaryType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PrimaryType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PrimaryType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PrimaryType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int intN;
   private java.lang.String stringN;
   private java.lang.Void nullN;
   private float floatN;
   private long longN;
   private boolean booleanN;
   private java.nio.ByteBuffer bytesN;
   private double doubleN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PrimaryType() {}

  /**
   * All-args constructor.
   * @param intN The new value for intN
   * @param stringN The new value for stringN
   * @param nullN The new value for nullN
   * @param floatN The new value for floatN
   * @param longN The new value for longN
   * @param booleanN The new value for booleanN
   * @param bytesN The new value for bytesN
   * @param doubleN The new value for doubleN
   */
  public PrimaryType(java.lang.Integer intN, java.lang.String stringN, java.lang.Void nullN, java.lang.Float floatN, java.lang.Long longN, java.lang.Boolean booleanN, java.nio.ByteBuffer bytesN, java.lang.Double doubleN) {
    this.intN = intN;
    this.stringN = stringN;
    this.nullN = nullN;
    this.floatN = floatN;
    this.longN = longN;
    this.booleanN = booleanN;
    this.bytesN = bytesN;
    this.doubleN = doubleN;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return intN;
    case 1: return stringN;
    case 2: return nullN;
    case 3: return floatN;
    case 4: return longN;
    case 5: return booleanN;
    case 6: return bytesN;
    case 7: return doubleN;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: intN = (java.lang.Integer)value$; break;
    case 1: stringN = value$ != null ? value$.toString() : null; break;
    case 2: nullN = (java.lang.Void)value$; break;
    case 3: floatN = (java.lang.Float)value$; break;
    case 4: longN = (java.lang.Long)value$; break;
    case 5: booleanN = (java.lang.Boolean)value$; break;
    case 6: bytesN = (java.nio.ByteBuffer)value$; break;
    case 7: doubleN = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'intN' field.
   * @return The value of the 'intN' field.
   */
  public int getIntN() {
    return intN;
  }


  /**
   * Sets the value of the 'intN' field.
   * @param value the value to set.
   */
  public void setIntN(int value) {
    this.intN = value;
  }

  /**
   * Gets the value of the 'stringN' field.
   * @return The value of the 'stringN' field.
   */
  public java.lang.String getStringN() {
    return stringN;
  }


  /**
   * Sets the value of the 'stringN' field.
   * @param value the value to set.
   */
  public void setStringN(java.lang.String value) {
    this.stringN = value;
  }

  /**
   * Gets the value of the 'nullN' field.
   * @return The value of the 'nullN' field.
   */
  public java.lang.Void getNullN() {
    return nullN;
  }


  /**
   * Sets the value of the 'nullN' field.
   * @param value the value to set.
   */
  public void setNullN(java.lang.Void value) {
    this.nullN = value;
  }

  /**
   * Gets the value of the 'floatN' field.
   * @return The value of the 'floatN' field.
   */
  public float getFloatN() {
    return floatN;
  }


  /**
   * Sets the value of the 'floatN' field.
   * @param value the value to set.
   */
  public void setFloatN(float value) {
    this.floatN = value;
  }

  /**
   * Gets the value of the 'longN' field.
   * @return The value of the 'longN' field.
   */
  public long getLongN() {
    return longN;
  }


  /**
   * Sets the value of the 'longN' field.
   * @param value the value to set.
   */
  public void setLongN(long value) {
    this.longN = value;
  }

  /**
   * Gets the value of the 'booleanN' field.
   * @return The value of the 'booleanN' field.
   */
  public boolean getBooleanN() {
    return booleanN;
  }


  /**
   * Sets the value of the 'booleanN' field.
   * @param value the value to set.
   */
  public void setBooleanN(boolean value) {
    this.booleanN = value;
  }

  /**
   * Gets the value of the 'bytesN' field.
   * @return The value of the 'bytesN' field.
   */
  public java.nio.ByteBuffer getBytesN() {
    return bytesN;
  }


  /**
   * Sets the value of the 'bytesN' field.
   * @param value the value to set.
   */
  public void setBytesN(java.nio.ByteBuffer value) {
    this.bytesN = value;
  }

  /**
   * Gets the value of the 'doubleN' field.
   * @return The value of the 'doubleN' field.
   */
  public double getDoubleN() {
    return doubleN;
  }


  /**
   * Sets the value of the 'doubleN' field.
   * @param value the value to set.
   */
  public void setDoubleN(double value) {
    this.doubleN = value;
  }

  /**
   * Creates a new PrimaryType RecordBuilder.
   * @return A new PrimaryType RecordBuilder
   */
  public static congnghetuts.com.avro.PrimaryType.Builder newBuilder() {
    return new congnghetuts.com.avro.PrimaryType.Builder();
  }

  /**
   * Creates a new PrimaryType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PrimaryType RecordBuilder
   */
  public static congnghetuts.com.avro.PrimaryType.Builder newBuilder(congnghetuts.com.avro.PrimaryType.Builder other) {
    if (other == null) {
      return new congnghetuts.com.avro.PrimaryType.Builder();
    } else {
      return new congnghetuts.com.avro.PrimaryType.Builder(other);
    }
  }

  /**
   * Creates a new PrimaryType RecordBuilder by copying an existing PrimaryType instance.
   * @param other The existing instance to copy.
   * @return A new PrimaryType RecordBuilder
   */
  public static congnghetuts.com.avro.PrimaryType.Builder newBuilder(congnghetuts.com.avro.PrimaryType other) {
    if (other == null) {
      return new congnghetuts.com.avro.PrimaryType.Builder();
    } else {
      return new congnghetuts.com.avro.PrimaryType.Builder(other);
    }
  }

  /**
   * RecordBuilder for PrimaryType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PrimaryType>
    implements org.apache.avro.data.RecordBuilder<PrimaryType> {

    private int intN;
    private java.lang.String stringN;
    private java.lang.Void nullN;
    private float floatN;
    private long longN;
    private boolean booleanN;
    private java.nio.ByteBuffer bytesN;
    private double doubleN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(congnghetuts.com.avro.PrimaryType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.intN)) {
        this.intN = data().deepCopy(fields()[0].schema(), other.intN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.stringN)) {
        this.stringN = data().deepCopy(fields()[1].schema(), other.stringN);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.nullN)) {
        this.nullN = data().deepCopy(fields()[2].schema(), other.nullN);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.floatN)) {
        this.floatN = data().deepCopy(fields()[3].schema(), other.floatN);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.longN)) {
        this.longN = data().deepCopy(fields()[4].schema(), other.longN);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.booleanN)) {
        this.booleanN = data().deepCopy(fields()[5].schema(), other.booleanN);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.bytesN)) {
        this.bytesN = data().deepCopy(fields()[6].schema(), other.bytesN);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.doubleN)) {
        this.doubleN = data().deepCopy(fields()[7].schema(), other.doubleN);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing PrimaryType instance
     * @param other The existing instance to copy.
     */
    private Builder(congnghetuts.com.avro.PrimaryType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.intN)) {
        this.intN = data().deepCopy(fields()[0].schema(), other.intN);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stringN)) {
        this.stringN = data().deepCopy(fields()[1].schema(), other.stringN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nullN)) {
        this.nullN = data().deepCopy(fields()[2].schema(), other.nullN);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.floatN)) {
        this.floatN = data().deepCopy(fields()[3].schema(), other.floatN);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.longN)) {
        this.longN = data().deepCopy(fields()[4].schema(), other.longN);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.booleanN)) {
        this.booleanN = data().deepCopy(fields()[5].schema(), other.booleanN);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bytesN)) {
        this.bytesN = data().deepCopy(fields()[6].schema(), other.bytesN);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.doubleN)) {
        this.doubleN = data().deepCopy(fields()[7].schema(), other.doubleN);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'intN' field.
      * @return The value.
      */
    public int getIntN() {
      return intN;
    }


    /**
      * Sets the value of the 'intN' field.
      * @param value The value of 'intN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setIntN(int value) {
      validate(fields()[0], value);
      this.intN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'intN' field has been set.
      * @return True if the 'intN' field has been set, false otherwise.
      */
    public boolean hasIntN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'intN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearIntN() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'stringN' field.
      * @return The value.
      */
    public java.lang.String getStringN() {
      return stringN;
    }


    /**
      * Sets the value of the 'stringN' field.
      * @param value The value of 'stringN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setStringN(java.lang.String value) {
      validate(fields()[1], value);
      this.stringN = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'stringN' field has been set.
      * @return True if the 'stringN' field has been set, false otherwise.
      */
    public boolean hasStringN() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'stringN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearStringN() {
      stringN = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nullN' field.
      * @return The value.
      */
    public java.lang.Void getNullN() {
      return nullN;
    }


    /**
      * Sets the value of the 'nullN' field.
      * @param value The value of 'nullN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setNullN(java.lang.Void value) {
      validate(fields()[2], value);
      this.nullN = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nullN' field has been set.
      * @return True if the 'nullN' field has been set, false otherwise.
      */
    public boolean hasNullN() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nullN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearNullN() {
      nullN = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'floatN' field.
      * @return The value.
      */
    public float getFloatN() {
      return floatN;
    }


    /**
      * Sets the value of the 'floatN' field.
      * @param value The value of 'floatN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setFloatN(float value) {
      validate(fields()[3], value);
      this.floatN = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'floatN' field has been set.
      * @return True if the 'floatN' field has been set, false otherwise.
      */
    public boolean hasFloatN() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'floatN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearFloatN() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'longN' field.
      * @return The value.
      */
    public long getLongN() {
      return longN;
    }


    /**
      * Sets the value of the 'longN' field.
      * @param value The value of 'longN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setLongN(long value) {
      validate(fields()[4], value);
      this.longN = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'longN' field has been set.
      * @return True if the 'longN' field has been set, false otherwise.
      */
    public boolean hasLongN() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'longN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearLongN() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'booleanN' field.
      * @return The value.
      */
    public boolean getBooleanN() {
      return booleanN;
    }


    /**
      * Sets the value of the 'booleanN' field.
      * @param value The value of 'booleanN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setBooleanN(boolean value) {
      validate(fields()[5], value);
      this.booleanN = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'booleanN' field has been set.
      * @return True if the 'booleanN' field has been set, false otherwise.
      */
    public boolean hasBooleanN() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'booleanN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearBooleanN() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'bytesN' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBytesN() {
      return bytesN;
    }


    /**
      * Sets the value of the 'bytesN' field.
      * @param value The value of 'bytesN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setBytesN(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.bytesN = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'bytesN' field has been set.
      * @return True if the 'bytesN' field has been set, false otherwise.
      */
    public boolean hasBytesN() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'bytesN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearBytesN() {
      bytesN = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'doubleN' field.
      * @return The value.
      */
    public double getDoubleN() {
      return doubleN;
    }


    /**
      * Sets the value of the 'doubleN' field.
      * @param value The value of 'doubleN'.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder setDoubleN(double value) {
      validate(fields()[7], value);
      this.doubleN = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'doubleN' field has been set.
      * @return True if the 'doubleN' field has been set, false otherwise.
      */
    public boolean hasDoubleN() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'doubleN' field.
      * @return This builder.
      */
    public congnghetuts.com.avro.PrimaryType.Builder clearDoubleN() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PrimaryType build() {
      try {
        PrimaryType record = new PrimaryType();
        record.intN = fieldSetFlags()[0] ? this.intN : (java.lang.Integer) defaultValue(fields()[0]);
        record.stringN = fieldSetFlags()[1] ? this.stringN : (java.lang.String) defaultValue(fields()[1]);
        record.nullN = fieldSetFlags()[2] ? this.nullN : (java.lang.Void) defaultValue(fields()[2]);
        record.floatN = fieldSetFlags()[3] ? this.floatN : (java.lang.Float) defaultValue(fields()[3]);
        record.longN = fieldSetFlags()[4] ? this.longN : (java.lang.Long) defaultValue(fields()[4]);
        record.booleanN = fieldSetFlags()[5] ? this.booleanN : (java.lang.Boolean) defaultValue(fields()[5]);
        record.bytesN = fieldSetFlags()[6] ? this.bytesN : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.doubleN = fieldSetFlags()[7] ? this.doubleN : (java.lang.Double) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PrimaryType>
    WRITER$ = (org.apache.avro.io.DatumWriter<PrimaryType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PrimaryType>
    READER$ = (org.apache.avro.io.DatumReader<PrimaryType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.intN);

    out.writeString(this.stringN);

    out.writeNull();

    out.writeFloat(this.floatN);

    out.writeLong(this.longN);

    out.writeBoolean(this.booleanN);

    out.writeBytes(this.bytesN);

    out.writeDouble(this.doubleN);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.intN = in.readInt();

      this.stringN = in.readString();

      in.readNull();

      this.floatN = in.readFloat();

      this.longN = in.readLong();

      this.booleanN = in.readBoolean();

      this.bytesN = in.readBytes(this.bytesN);

      this.doubleN = in.readDouble();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.intN = in.readInt();
          break;

        case 1:
          this.stringN = in.readString();
          break;

        case 2:
          in.readNull();
          break;

        case 3:
          this.floatN = in.readFloat();
          break;

        case 4:
          this.longN = in.readLong();
          break;

        case 5:
          this.booleanN = in.readBoolean();
          break;

        case 6:
          this.bytesN = in.readBytes(this.bytesN);
          break;

        case 7:
          this.doubleN = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










